### ISSUE TITLE
Add support for different keyboard layouts 

### ISSUE THREAD

**Issue by Shoggomo** [Danesprite/dragonfly#16]
Right now different keyboard layouts can cause problems like not being able to write `{}` with `Text()`. 
In [Monospark's fork](https://github.com/Monospark/dragonfire) this bug was fixed with ebc094c69ad364b1c217b9e6d4af23aa97711314. This should be fixed here, too.

**Comment by Danesprite** [comment]
Thanks for that. I'll make a PR to merge that change without the other changes in his fork.

**Comment by Danesprite** [comment]
This works nicely, although I uncovered an interesting Windows limitation while testing it: switching between and using multiple layouts doesn't work properly for layouts other than what the process started with. This appears to be due to Windows storing locale information like this with each thread and not updating it on a layout change by the user.

This can be fixed by calling `GetKeyboardLayout`  in a new thread and using the updated value in the `Keyboard` class, although I'm not sure if this other problem is worth fixing really.
